site_name: Digi Handboek
site_url: https://digigilde.github.io/handboek/
site_description: In het Digi Handboek vind je handige informatie over hoe zaken bij het Digi Gilde zijn geregeld.
copyright: European Union Public License v. 1.2

nav:
  - Digi Handboek: index.md
  - Onze werkwijze:
      - Principes: werkwijze/principes.md
      - Bijdragen aan het Digi Handboek: bijdragen-aan-handboek.md
      - Beslissingen logboek: werkwijze/beslissingen-logboek.md
      - Code review: werkwijze/code-review.md
  - Onboarding:
      - Je eerste dagen: onboarding/eerste-dagen.md
      - Dev machine: onboarding/dev-machine.md
      - Accounts: onboarding/accounts.md
      - Offboarding: offboarding.md

theme:
  name: material
  logo: assets/logo_digi_gilde.svg
  favicon: assets/logo_digi_gilde.svg
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to auto mode
  icon:
    annotation: fontawesome/solid/circle-info
  language: nl

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DigiGilde/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/rijksictgilde/
    - icon: fontawesome/solid/globe
      link: https://rijksictgilde.nl/

extra_templates:
  - .well-known/security.txt

extra_css:
  - stylesheets/digigilde.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      timezone: Europe/Amsterdam
      locale: nl
  - glightbox
  - privacy
  - search

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
